const fruits = [
  {
    id: 1,
    name: "Apple",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/300px-Red_Apple.jpg",
    description: "A sweet, crunchy fruit widely consumed around the world.",
    nativeTo: ["Central Asia"],
    benefits: ["High in fiber", "Supports heart health"],
    scientificName: "Malus domestica",
  },
  {
    id: 2,
    name: "Banana",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/300px-Banana-Single.jpg",
    description: "A soft and sweet fruit rich in carbohydrates.",
    nativeTo: ["Southeast Asia"],
    benefits: ["Quick energy", "Rich in potassium"],
    scientificName: "Musa",
  },
  {
    id: 3,
    name: "Mango",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/300px-Hapus_Mango.jpg",
    description: "A tropical stone fruit with juicy pulp.",
    nativeTo: ["India","Myanmar"],
    benefits: ["Vitamin A", "Boosts immunity"],
    scientificName: "Mangifera indica",
  },
  {
    id: 4,
    name: "Orange",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Orange-Fruit-Pieces.jpg/300px-Orange-Fruit-Pieces.jpg",
    description: "A citrus fruit with tangy flavor.",
    nativeTo: ["Asia"],
    benefits: ["Vitamin C", "Skin health"],
    scientificName: "Citrus sinensis",
  },
  {
    id: 5,
    name: "Grapes",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_white.jpg/300px-Table_grapes_on_white.jpg",
    description: "Small juicy fruits growing in clusters.",
    nativeTo: ["Mediterranean"],
    benefits: ["Antioxidants", "Heart health"],
    scientificName: "Vitis vinifera",
  },
  {
    id: 6,
    name: "Pineapple",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Pineapple_and_cross_section.jpg/300px-Pineapple_and_cross_section.jpg",
    description: "A tropical fruit with spiky skin.",
    nativeTo: ["South America"],
    benefits: ["Digestion", "Anti-inflammatory"],
    scientificName: "Ananas comosus",
  },
  {
    id: 7,
    name: "Strawberry",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/300px-PerfectStrawberry.jpg",
    description: "A bright red fruit with seeds on the outside.",
    nativeTo: ["Europe"],
    benefits: ["Vitamin C", "Heart health"],
    scientificName: "Fragaria × ananassa",
  },
  {
    id: 8,
    name: "Watermelon",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Watermelon_cross_BNC.jpg/300px-Watermelon_cross_BNC.jpg",
    description: "A refreshing fruit with high water content.",
    nativeTo: ["Africa"],
    benefits: ["Hydration", "Cooling effect"],
    scientificName: "Citrullus lanatus",
  },
  {
    id: 9,
    name: "Papaya",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Papaya_cross_section_BNC.jpg/300px-Papaya_cross_section_BNC.jpg",
    description: "A tropical fruit with orange flesh.",
    nativeTo: ["Central America"],
    benefits: ["Digestion", "Immunity"],
    scientificName: "Carica papaya",
  },
  {
    id: 10,
    name: "Guava",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Guava_ID.jpg/300px-Guava_ID.jpg",
    description: "A fragrant tropical fruit.",
    nativeTo: ["Central America"],
    benefits: ["Very high vitamin C", "Gut health"],
    scientificName: "Psidium guajava",
  },
  {
    id: 11,
    name: "Kiwi",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kiwi_aka.jpg/300px-Kiwi_aka.jpg",
    description: "A small fruit with green flesh.",
    nativeTo: ["China"],
    benefits: ["Digestion", "Immunity"],
    scientificName: "Actinidia deliciosa",
  },
  {
    id: 12,
    name: "Cherry",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Cherry_Stella444.jpg/300px-Cherry_Stella444.jpg",
    description: "A small stone fruit.",
    nativeTo: ["Europe"],
    benefits: ["Anti-inflammatory", "Sleep support"],
    scientificName: "Prunus avium",
  },
  {
    id: 13,
    name: "Peach",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Nectarine_and_cross_section02_edit.jpg/300px-Nectarine_and_cross_section02_edit.jpg",
    description: "A soft and juicy fruit.",
    nativeTo: ["China"],
    benefits: ["Skin health", "Digestion"],
    scientificName: "Prunus persica",
  },
  {
    id: 14,
    name: "Pear",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Pear_DS.jpg/300px-Pear_DS.jpg",
    description: "A sweet bell-shaped fruit.",
    nativeTo: ["Europe"],
    benefits: ["High fiber", "Gut health"],
    scientificName: "Pyrus",
  },
  {
    id: 15,
    name: "Plum",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Plums.jpg/300px-Plums.jpg",
    description: "A juicy fruit with smooth skin.",
    nativeTo: ["Asia"],
    benefits: ["Digestive health", "Antioxidants"],
    scientificName: "Prunus domestica",
  },
  {
    id: 16,
    name: "Blueberry",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Blueberries.jpg/300px-Blueberries.jpg",
    description: "A small blue berry rich in antioxidants.",
    nativeTo: ["North America"],
    benefits: ["Brain health", "Heart health"],
    scientificName: "Vaccinium corymbosum",
  },
  {
    id: 17,
    name: "Raspberry",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Raspberries05.jpg/300px-Raspberries05.jpg",
    description: "A soft red berry.",
    nativeTo: ["Europe"],
    benefits: ["High fiber", "Weight management"],
    scientificName: "Rubus idaeus",
  },
  {
    id: 18,
    name: "Blackberry",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Blackberries.jpg/300px-Blackberries.jpg",
    description: "A dark berry with rich flavor.",
    nativeTo: ["Europe"],
    benefits: ["Immunity", "Brain health"],
    scientificName: "Rubus fruticosus",
  },
  {
    id: 19,
    name: "Lemon",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Lemon.jpg/300px-Lemon.jpg",
    description: "A sour citrus fruit.",
    nativeTo: ["Asia"],
    benefits: ["Vitamin C", "Detoxifying"],
    scientificName: "Citrus limon",
  },
  {
    id: 20,
    name: "Lime",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Lime.jpg/300px-Lime.jpg",
    description: "A green citrus fruit.",
    nativeTo: ["Asia"],
    benefits: ["Immunity", "Skin health"],
    scientificName: "Citrus aurantiifolia",
  },
  {
    id: 21,
    name: "Grapefruit",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Grapefruit-Whole-%26-Split.jpg/300px-Grapefruit-Whole-%26-Split.jpg",
    description: "A tangy citrus fruit.",
    nativeTo: ["Caribbean"],
    benefits: ["Vitamin C", "Weight management"],
    scientificName: "Citrus × paradisi",
  },
  {
    id: 22,
    name: "Pomegranate",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_JE2.jpg/300px-Pomegranate_JE2.jpg",
    description: "A fruit with juicy seeds.",
    nativeTo: ["Iran"],
    benefits: ["Antioxidants", "Heart health"],
    scientificName: "Punica granatum",
  },
  {
    id: 23,
    name: "Avocado",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Avocado_with_cross_section.jpg/300px-Avocado_with_cross_section.jpg",
    description: "A creamy fruit rich in healthy fats.",
    nativeTo: ["Mexico"],
    benefits: ["Good fats", "Heart health"],
    scientificName: "Persea americana",
  },
  {
    id: 24,
    name: "Fig",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Fig_fruit.jpg/300px-Fig_fruit.jpg",
    description: "A soft fruit with many seeds.",
    nativeTo: ["Middle East"],
    benefits: ["Digestion", "Bone health"],
    scientificName: "Ficus carica",
  },
  {
    id: 25,
    name: "Date",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Khadrawy_dates.jpg/300px-Khadrawy_dates.jpg",
    description: "A sweet dried fruit.",
    nativeTo: ["Middle East"],
    benefits: ["Energy", "Minerals"],
    scientificName: "Phoenix dactylifera",
  },
  {
    id: 26,
    name: "Coconut",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Coconut.jpg/300px-Coconut.jpg",
    description: "A tropical fruit with hard shell.",
    nativeTo: ["Indo-Pacific"],
    benefits: ["Hydration", "Healthy fats"],
    scientificName: "Cocos nucifera",
  },
  {
    id: 27,
    name: "Apricot",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Apricot_fruit.jpg/300px-Apricot_fruit.jpg",
    description: "A small orange stone fruit.",
    nativeTo: ["China"],
    benefits: ["Eye health", "Fiber"],
    scientificName: "Prunus armeniaca",
  },
  {
    id: 28,
    name: "Cantaloupe",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cantaloupe_and_cross_section.jpg/300px-Cantaloupe_and_cross_section.jpg",
    description: "A sweet orange-fleshed melon.",
    nativeTo: ["Africa"],
    benefits: ["Hydration", "Vitamins"],
    scientificName: "Cucumis melo",
  },
  {
    id: 29,
    name: "Honeydew",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Honeydew.jpg/300px-Honeydew.jpg",
    description: "A pale green melon.",
    nativeTo: ["Africa"],
    benefits: ["Low calorie", "Vitamin C"],
    scientificName: "Cucumis melo",
  },
  {
    id: 30,
    name: "Tangerine",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Tangerines.jpg/300px-Tangerines.jpg",
    description: "A small sweet citrus fruit.",
    nativeTo: ["China"],
    benefits: ["Vitamin C", "Easy digestion"],
    scientificName: "Citrus reticulata",
  },
];

export default fruits;